import express from 'express';
import * as siteCtrl from '../controllers/site.controller';
import isAuthenticated from '../middlewares/authenticate';
import validate from '../config/joi.validate';
import schema from '../utils/validator';

const router = express.Router();

/**
 * @swagger
 * tags:
 *   - name: site
 *     description: Site operations
 */

/**
 * @swagger
 * definitions:
 *   Site:
 *     type: object
 *     properties:
 *       id:
 *         type: integer
 *         description: Unique identifier representing a specific site
 *         example: 2
 *       first_name:
 *         type: string
 *         description: first name of the site
 *         example: Krishna
 *       last_name:
 *         type: string
 *         description: last name of the site
 *         example: Timilsina
 *       email:
 *         type: string
 *         description: email of the site
 *         required: true
 *         example: test@gmail.com
 *       password:
 *         type: string
 *         description: password of the site
 *         required: true
 *         example: "1234"
 *       status:
 *         type: integer
 *         description: status of the site
 *         example: 1
 *       created_at:
 *         type: string
 *         format: date-time
 *         description: Site creation datetime
 *       updated_at:
 *         type: string
 *         format: date-time
 *         description: Site update datetime
 *   Error:
 *     type: object
 *     properties:
 *        message:
 *           type: string
 *        error:
 *           type: boolean
 *           default: true
 */

/**
 * @swagger
 * securityDefinitions:
 *   Bearer:
 *     description: |
 *            For accessing the API a valid JWT token must be passed in all the queries in
 *            the 'Authorization' header.
 *
 *
 *            A valid JWT token is generated by the API and returned as answer of a call
 *            to the route /auth/login giving a valid site & password.
 *
 *
 *            The following syntax must be used in the 'Authorization' header:
 *
 *            Bearer xxxxxx.yyyyyyy.zzzzzz
 *     type: apiKey
 *     name: Authorization
 *     in: header
 *
 */

router.route('/')

/**
 * @swagger
 * /sites:
 *   post:
 *     tags:
 *       - site
 *     summary: "Create a new site"
 *     security:
 *        - Bearer: []
 *     operationId: storeSite
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters:
 *       - name: body
 *         in: body
 *         description: Created site object
 *         required: true
 *         schema:
 *           $ref: "#/definitions/Site"
 *     responses:
 *       200:
 *         description: OK
 *         schema:
 *           $ref: "#/definitions/Site"
 *       403:
 *          description: Site not found
 *          schema:
 *             $ref: '#/definitions/Error'
 */

    .post(validate(schema.storeSite), (req, res) => {
        siteCtrl.store(req, res);
    })

    /**
     * @swagger
     * /sites:
     *   get:
     *     tags:
     *       - site
     *     summary: "List all sites"
     *     operationId: findAll
     *     consumes:
     *       - application/json
     *     produces:
     *       - application/json
     *     parameters: []
     *     responses:
     *       200:
     *         description: OK
     *         schema:
     *            type: object
     */

    .get( (req, res) => {
        siteCtrl.findAll(req, res);
    });


router.route('/:id')

/**
 * @swagger
 * /sites/{id}:
 *   get:
 *     tags:
 *       - site
 *     summary: Find the site by ID
 *     operationId: findById
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters:
 *       - name: id
 *         in: path
 *         description: id of site that needs to be fetched
 *         required: true
 *         type: integer
 *     responses:
 *       200:
 *         description: OK
 *         schema:
 *           $ref: "#/definitions/Site"
 *       404:
 *          description: Site not found
 *          schema:
 *             $ref: '#/definitions/Error'
 */

    .get( (req, res) => {
        siteCtrl.findById(req, res);
    })

    /**
     * @swagger
     * /sites/{id}:
     *   put:
     *     tags:
     *       - site
     *     summary: "Update an existing site by ID"
     *     security:
     *       - Bearer: []
     *     operationId: update
     *     consumes:
     *       - application/json
     *     produces:
     *       - application/json
     *     parameters:
     *       - name: id
     *         in: path
     *         description: id that need to be updated
     *         required: true
     *         type: integer
     *       - name: body
     *         in: body
     *         description: Updated site object
     *         required: true
     *         schema:
     *           $ref: "#/definitions/Site"
     *     responses:
     *       200:
     *         description: OK
     *         schema:
     *           $ref: "#/definitions/Site"
     *       400:
     *         description: Invalid site
     */

    .put(isAuthenticated, (req, res) => {
        siteCtrl.update(req, res);
    })

    /**
     * @swagger
     * /sites/{id}:
     *   delete:
     *     tags:
     *       - site
     *     summary: Delete the site by ID
     *     security:
     *       - Bearer: []
     *     operationId: destroy
     *     produces:
     *       - application/json
     *     parameters:
     *       - name: id
     *         in: path
     *         description: id of site that needs to be deleted
     *         required: true
     *         type: integer
     *     responses:
     *       200:
     *         description: OK
     *       400:
     *          description: "Invalid ID"
     */

    .delete(isAuthenticated, (req, res) => {
        siteCtrl.destroy(req, res);
    });


export default router;